<?php

namespace MoiKubki\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUnitRepository extends EntityRepository
{
}
