<?php

namespace MoiKubki\FootballBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamFCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamFCRepository extends EntityRepository
{
}
